### ISSUE TITLE
Search function for post types not working after loading autolink.

### ISSUE THREAD

**Issue by ndemous-eastwest** [thecodezone/disciple-tools-autolink#2]
I loaded the release zip onto our demo site at dtdemo1.wpengine.com and noticed that it seems to disable the searches for the post types (contact, group, etc) so that when you go to the search screen it just hangs.  I included an image below.  I can give you an admin user on the demo site if you want to check it out.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/85511606/200681102-f8a88bf4-7e6a-46c2-9c6c-443833454c31.png">

**Comment by micahmills** [comment]
This is now fixed in the development branch. It should merge into master in the next release.
