### ISSUE TITLE
P2P not initialized in magic links

### ISSUE THREAD

**Issue by incraigulous** [thecodezone/disciple-tools-autolink#4]
WP P2P does not seem to be initialized in the user app magic link.

See https://github.com/thecodezone/disciple-tools-autolink/blob/f968f8adc8a5ad7be9273b904be9cc67af4d5c34/magic-link/magic-link-user-app.php#L337

We are trying to a create a group. It works, but whenever we try to create the group with the members and leaders fields populated we get an error because there are no P2P connections registered. 

```
$fields = [
            "title" => $name,
            "members" => [
                "values" => [
                    [ "value" => $users_contact_id ]
                ]
            ],
            "leaders" => [
                "values" => [
                    [ "value" => $users_contact_id ]
                ]
            ]
        ];
        $group = DT_Posts::create_post( 'groups', $fields, false, false );
```        
        
If I run that randomly in the theme it works, when I run it in my magic link we get:

```
PHP Fatal error:  Uncaught Error: Call to a member function connect() on bool in /Users/micahmills/Desktop/Sites/DT/app/public/wp-content/themes/disciple-tools-theme/dt-posts/posts.php:2248
```

If I remove the members and leaders parts of the array it works. It appears to be something with the p2p connection registration. I also checked I am able to create the same post through the API, but for some reason this isn’t working.

We tried running this in the `dt_blank_body`, `init`, `wp_loaded `, and `after_setup_theme` hooks. It seems that `wp_loaded` is never even fired in the magic link request, but that is where p2p is initialized here: https://github.com/DiscipleTools/disciple-tools-theme/blob/master/dt-core/libraries/posts-to-posts/posts-to-posts.php. 

I tried to run `p2p_register_connection_type` manually to register the connections I needed just for this request, but I get an error saying `Connection types should not be registered before the "init" hook`.

I'm adding the connections with raw SQL queries as a workaround, but that isn't a great solution because no connection hooks will be fired. For example, the group member and leader connections are in place, but the group leaders don't show up in the group leader field on the DT group view, though it does in the group index view.

**Comment by corsacca** [comment]
@incraigulous @micahmills 
Experiment:
try running `DT_Posts::get_post_field_settings( 'groups', false )` before that create to refresh the cached fields object

**Comment by micahmills** [comment]
Just tried this and still get the same error

**Comment by micahmills** [comment]
The most recent update to DT (https://github.com/DiscipleTools/disciple-tools-theme/commit/a80c983788d410897742807ae1189fe55c3fcbc9) fixes the issue.

**Comment by incraigulous** [comment]
@corsacca, you're the best! Thank you SO much for the fix!

**Comment by corsacca** [comment]
Thanks :)
